---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"

# add your repo's dependabot configuration here
