name: Liquibase Dev Deploy

on:
  workflow_dispatch:

env:
  DATABRICKS_HOST: "hginsights-dev.cloud.databricks.com"
  DATABRICKS_WAREHOUSE: "0dc0fd8c15df8ad7" # TODO: Add the warehouse here
  # TODO: This needs to be tested once we're in a repo that can actually use the SP - not my personal repo
#  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_SP_ID }}
#  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_SP_SECRET }}
  DATABRICKS_OAUTH_TOKEN: ${{ secrets.DATABRICKS_OAUTH_TOKEN }}

jobs:
  generate-and-approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write       # required by manual-approval
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Liquibase
        uses: liquibase/setup-liquibase@v2
        with:
          version: '5.0.1'
          edition: 'oss'

      - name: Install Databricks Drivers
        run: liquibase lpm install

#      - name: Get Databricks token
#        id: token
#        run: |
#          token_response=$(curl -s -X POST "https://${{ env.DATABRICKS_INSTANCE }}/oidc/v1/token" \
#            -u "${{ env.DATABRICKS_CLIENT_ID }}:${{ env.DATABRICKS_CLIENT_SECRET }}" \
#            --data 'grant_type=client_credentials')
#
#          echo "DATABRICKS_OAUTH_TOKEN=$(echo $token_response | jq -r .access_token)" >> $GITHUB_ENV

      # TODO change "mac_liquibase_test" as the default schema in the URL string
      - name: Run Liquibase update-sql
        run: |
          liquibase --url="jdbc:databricks://${{ env.DATABRICKS_HOST }}:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/${{ env.DATABRICKS_WAREHOUSE }};ConnCatalog=dev;ConnSchema=mac_liquibase_test" --username="token" --password="${{ env.DATABRICKS_OAUTH_TOKEN }}" --changelogFile="master-changelog.yml" update-sql > update_sql.sql

          {
            echo 'body<<EOF'
            cat update_sql.sql
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mhollisterhg # TODO: Expand this out to a User Group of people who are approved to apply migrations to production tables
          issue-title: "Liquibase SQL Approval" # TODO Make this better / dynamic
          minimum-approvals: 1
          issue-body: |
            **Liquibase update-sql output:**

            ```
            ${{ steps.liquibase.outputs.body }}
            ```

      - name: Run Liquibase update
        run: |
          liquibase --url="jdbc:databricks://${{ env.DATABRICKS_HOST }}:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/${{ env.DATABRICKS_WAREHOUSE }};ConnCatalog=dev;ConnSchema=mac_liquibase_test" --username="token" --password="${{ env.DATABRICKS_OAUTH_TOKEN }}" --changelogFile="master-changelog.yml" update
