name: Liquibase Prod Deploy

on:
  workflow_dispatch:

jobs:
  generate-and-approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write       # required by manual-approval
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run Liquibase update-sql
        id: liquibase
        run: |
          # Run Liquibase to generate the SQL
          printf "dummy_sql first line\ndummy_sql second line\ndummy_sql third line" > update.sql

          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat "line 1" >> $GITHUB_OUTPUT
          cat "line 2" >> $GITHUB_OUTPUT
          cat "line 3" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check output
        run: |
          echo ${{ steps.liquibase.outputs.body }}

#      - name: Manual approval
#        uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ github.TOKEN }}
#          approvers: mhollisterhg
#          issue-title: "Liquibase SQL Approval"
#          minimum-approvals: 1
#          issue-body: |
#            **Liquibase update-sql output:**
#
#            ```
#            ${{ steps.liquibase.outputs.body }}
#            ```
