name: Liquibase Prod Deploy

on:
  workflow_dispatch:

jobs:
  generate-and-approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write       # required by manual-approval
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Java 17 is required for Liquibase version 5
      # Maybe don't need this with the official action?
#      - name: Set up Java 17
#        uses: hgdata/setup-java@v4
#        with:
#          java-version: 17
#          distribution: temurin

      # Install liquibase
      - uses: liquibase/setup-liquibase@v2
        with:
          version: '5.0.1'
          edition: 'oss'

      - name: Install Databricks Drivers
        run: liquibase lpm install

      - name: Run Liquibase update-sql
        id: liquibase
        run: |
          liquibase --version > test.txt

          {
            echo 'body<<EOF'
            cat test.txt
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Check output
        run: |
          echo "${{ steps.liquibase.outputs.body }}"

      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mhollisterhg # TODO: Expand this out to a User Group of people who are approved to apply migrations to production tables
          issue-title: "Liquibase SQL Approval" # TODO Make this better / dynamic
          minimum-approvals: 1
          issue-body: |
            **Liquibase update-sql output:**

            ```
            ${{ steps.liquibase.outputs.body }}
            ```
